# Generated by Django 4.0 on 2023-03-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_foods_image_alter_foods_add_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images'),
        ),
    ]
