# Generated by Django 4.0 on 2023-03-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_foods_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='rating',
        ),
    ]
