# Generated by Django 4.0 on 2023-03-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_alter_foods_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='category',
            field=models.CharField(default='something_to_eat', max_length=30),
        ),
    ]
