# Generated by Django 4.0 on 2023-03-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_foods_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(max_length=11)),
                ('sign_up_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
