# Generated by Django 4.0 on 2023-03-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_alter_users_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
